-- for MYSQL 5.7
CREATE TABLE GENERIC_CLOB (
    USER_ID int NOT NULL, 
    CLOB_ID int NOT NULL AUTO_INCREMENT, 
    CLOB_KEY nvarchar(255),
    RECENT_VERSION int,
    CONTENT MEDIUMTEXT CHARACTER SET utf8,
    PRIMARY KEY (clob_id),
    FOREIGN KEY (user_id) REFERENCES USERS(id)
);

