-- for MYSQL 5.7

CREATE TABLE BEARER_TOKEN (
    USER_ID int NOT NULL, 
    TOKEN_ID int NOT NULL AUTO_INCREMENT, 
    TOKEN_VALUE NVARCHAR(200) UNIQUE,
    EXPIRY_TIME DATETIME,
    PRIMARY KEY (TOKEN_ID),
    FOREIGN KEY (USER_ID) REFERENCES USERS(id)
);

CREATE TABLE REFRESH_TOKEN (
    USER_ID int NOT NULL, 
    TOKEN_ID int NOT NULL AUTO_INCREMENT, 
    TOKEN_VALUE NVARCHAR(200) UNIQUE,
    EXPIRY_TIME DATETIME,
    PRIMARY KEY (TOKEN_ID),
    FOREIGN KEY (USER_ID) REFERENCES USERS(id)
);



